### ISSUE TITLE
Your First Zenoh app examples don't work due to missing config

### ISSUE THREAD

**Issue by mattvalentine** [atolab/zenoh-web#66]
The examples in Your first Zenoh app do not work with version `eclipse-zenoh==1.0.0b2`

```
Traceback (most recent call last):
  File "z_sensor.py", line 11, in <module>
    session = zenoh.open()
TypeError: open() missing 1 required positional argument: 'config'
```

```
Traceback (most recent call last):
  File "z_subscriber.py", line 11, in <module>
    session = zenoh.open()
TypeError: open() missing 1 required positional argument: 'config'
```

**Comment by mattvalentine** [comment]
I figured out how to get it to run, and made a small pr https://github.com/atolab/zenoh-web/pull/67

**Comment by oteffahi** [comment]
Closed by https://github.com/atolab/zenoh-web/pull/67
